"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var mobile_1 = require("./mobile");
var myMobile = new mobile_1.Mobile("S21", "Galaxy", "Samsung", "Rojo", 384);
console.log('Name:', myMobile.getName());
console.log('Trademark:', myMobile.getTrademark());
console.log('Model:', myMobile.getModel());
console.log('Color:', myMobile.getColor());
console.log('Price:', myMobile.getPrice());
myMobile.impMob();
myMobile.setName('A34');
myMobile.setTrademark('Galaxy');
myMobile.setModel('Samsung');
myMobile.setColor('Amarillo');
myMobile.setPrice(260);
console.log('New name:', myMobile.getName());
console.log('New Trademark:', myMobile.getTrademark());
console.log('New Model:', myMobile.getModel());
console.log('New Color:', myMobile.getColor());
console.log('New Price:', myMobile.getPrice());
myMobile.impMob();
var myMobile2 = new mobile_1.Mobile("S21", "Galaxy", "Samsung", "Rojo", 384);
var myMobile3 = new mobile_1.Mobile("A54", "Galaxy", "Samsung", "Negro", 415);
var myMobiles = [myMobile, myMobile2, myMobile3];
myMobiles[0].impMob();
myMobiles[1].impMob();
myMobiles[2].impMob();
